### PR TITLE
PublisherService: Handle all type of exceptions when failing to publish

### PR DESCRIPTION
**Pull request by MrShish**

### CODE REVIEW

**Comment by MrShish** [comment]
Current implementation doesn't take in to account AmazonClientExceptions, thus, will miss if there is connectivity issues to aws. 
This will handle all types of unforseen exceptions, so if something exceptional happens: leave the message in the que.

**Comment by MrShish** [comment]
ping @xiaodong-izettle

**Comment by MrShish** [comment]
fyi: @ssprang

**Comment by xiaodong-izettle** [comment]
@MrShish, I paired programming with @nzroller for this PR: https://github.com/iZettle/sun/pull/7580.

It will solve the issue at hand. But I think this one is good anyway. :)

**Comment by xiaodong-izettle** [comment]
Nice and merging...

**Pull request merged**
