### PR TITLE
Upgrade dependencies.

### PR DESCRIPTION
**Pull request by xiaodong-izettle**
Ping @nzroller, are there anything else we need to change? Also for your information, @aaanders. 

Thanks. :)

### CODE REVIEW

**Comment by aaanders** [comment]
:heart:

**Comment by xiaodong-izettle** [comment]
Ping @nzroller, thanks. :)

**Comment by nzroller** [comment]
Nice man. :+1:

**Comment by xiaodong-izettle** [comment]
Thanks. :)

**Pull request merged**
