### PR TITLE
Use default consistency level

### PR DESCRIPTION
**Pull request by xiaodong-izettle**
The default consistency level from the driver is good enough for us... 

Also adding support to set `localDc` when creating cluster object...

Ping @x1a0, thanks...

### CODE REVIEW

**Comment by xiaodong-izettle** [comment]
Ping @x1a0, thanks... :)

**Comment by x1a0** [comment]
@xiaodong-izettle [Here](http://docs.datastax.com/en/drivers/java/3.0/com/datastax/driver/core/policies/DCAwareRoundRobinPolicy.html) says:
> If used with a single data center, this policy is equivalent to the RoundRobinPolicy, but its DC awareness incurs a slight overhead so the latter should be preferred to this policy in that case.

I think we only have single DC? Or are we preparing for multiDC here?

**Comment by xiaodong-izettle** [comment]
Hehe, @x1a0, we are using this `DCAwareRoundRobinPolicy` now, yes? And it seems the document is right that the overhead is really slight... :)

And yes, we only have single DC now. And we have to use multiDC sometime, like when migrating the cluster into VPC... Hope I made myself clear.. :)

**Comment by x1a0** [comment]
@xiaodong-izettle Yep - I was thinking if we only need single DC then changing to use `RoundRobinPolicy` instead of `DCAwareRoundRobinPolicy` as doc suggests.
Since multiDC is needed soon I think this is good.
Thanks - I am merging it.

**Comment by xiaodong-izettle** [comment]
Thanks for merging, @x1a0. :)

**Pull request merged**
