### PR TITLE
Preparation to upgrade Cassandra to 2.2.6

### PR DESCRIPTION
**Pull request by xiaodong-izettle**
Ping @nzroller, and F.Y.I @progre55, thanks...

### CODE REVIEW

**Comment by xiaodong-izettle** [comment]
PRs for `authentication`, `authorization` and `purchase` will come up...

**Comment by nzroller** [comment]
What exactly is the change here other than some good POM cleanup? Does it fix some stuff downstream?

**Comment by xiaodong-izettle** [comment]
It's more like a cleanup like you said. I just changed the scope of `astyanax-thrift`...

**Comment by xiaodong-izettle** [comment]
Thanks, @nzroller. :)

**Pull request merged**
