### PR TITLE
Increase AWS client retry times from 3 (default) to 6.

### PR DESCRIPTION
**Pull request by xiaodong-izettle**
For discussion: let's increase the retry time from 3 to 6, see if it helps? 

I searched for `MessagingManager NOT INFO` in Splunk for last 30 days, no results...

Ping @nzroller and @fredrikbackstrom, thanks...

### CODE REVIEW

**Comment by fredrikbackstrom** [comment]
ping @AndreasMeisingseth

**Comment by fredrikbackstrom** [comment]
@xiaodong-izettle then the failure is not logged since we are not handling the Future.error in Sun. 

I think it's worth doing this as it would at least limit the effect of network problems. It's a aid and let's find more solutions further on. 

I wonder though how this can be the root cause of the missing events problems as the default 3 would catch most.

**Comment by xiaodong-izettle** [comment]
@fredrikbackstrom, thanks for the comment. I assume the container would log for `EJBException` anyway... 

But just in case, I also check this in Splunk `AmazonHttpClient NOT INFO NOT "Unable to parse SQS queue URL" NOT host="batch-processing2" NOT host="riskapp1-ie-a" NOT "Will leave it on queue"` for last 30 days. 15 results, 8 from `app2-sp-b`, which should be fine, as Planet has a build-in solution, 7 from `izlvmdapp001`, which kinds of understandable, as that server is not ec2 instance...

**Comment by AndreasMeisingseth** [comment]
Nice!

**Comment by xiaodong-izettle** [comment]
And I agree with you, @fredrikbackstrom, that retrying 3 times should catch most.... 

The mismatch due to SQS/SNS should be very very few....

**Comment by xiaodong-izettle** [comment]
So @AndreasMeisingseth, it would be very helpful that, you could provide us some examples of the issue you mentioned, so that we could dig deep, to find the root cause... :)

**Comment by AndreasMeisingseth** [comment]
@xiaodong-izettle I'm preparing that for you, will send it over shortly (like tomorrow or so)

**Comment by xiaodong-izettle** [comment]
Thanks a lot in advance, @AndreasMeisingseth. :)

**Comment by xiaodong-izettle** [comment]
@AndreasMeisingseth, any updates?

**Comment by AndreasMeisingseth** [comment]
The updates I have is that it looks better than before (I've only looked at data from 2016-02-01 going forward) when we haven't experienced any SNS/SQS outages. We are only having single events missing, which is within the tolerance of what we can tolerate.

**Comment by AndreasMeisingseth** [comment]
With that said, I still think that this is the way forward, and in the event of time add a mechanism that makes us resilient to AWS SNS/SQS going down for longer periods (+1 minute). We have encountered that before, and will most likely do that again.

**Comment by xiaodong-izettle** [comment]
OK, thanks for the update, @AndreasMeisingseth. :)

**Comment by fredrikbackstrom** [comment]
So the move of SUN to AWS makes network communication to SNS/SQS more reliable. 

Then shall we still try this out or should we skip this and focus on solving the issue when the downtime is > 1 min.

**Comment by xiaodong-izettle** [comment]
IMHO, we just keep what we have for now... :)

I'll close this one, but feel free to open, if anyone thinks this is still what we need...

**Pull request closed without merging**
