### PR TITLE
Adds semaphores to sequence generator.

### PR DESCRIPTION
**Pull request by mikaellothman**
Semaphores have been added in order to decrease the number of concurrent
attempts to acquire distributed lock in Cassandra before sequence update.

### CODE REVIEW

**Comment by MrShish** [comment]
have you done some benchmarking?

**Comment by mikaellothman** [comment]
Yes, I have tested how it scales when you ramp up the number of concurrent requests. The old solution got slower the more concurrent requests we had (even the total throughput got a lot lower). The new solution keeps the same performance even if you ramp up the number of concurrent callers. 

I can follow up with the results, just give me a moment :)

**Comment by mikaellothman** [comment]
Ok. it's hard to get good reliable results without running hundreds of rounds with this test suite. However, you see the trend...

**New version (with semaphores):**
Size: 1, Time: 5
Size: 10, Time: 5
Size: 20, Time: 6
Size: 30, Time: 6
Size: 40, Time: 6
Size: 50, Time: 7
Size: 60, Time: 7
Size: 70, Time: 8
Size: 80, Time: 8
Size: 90, Time: 8
Size: 100, Time: 9
Size: 1000, Time: 9

**Old version:**
Size: 1, Time: 2
Size: 10, Time: 10
Size: 20, Time: 11
Size: 30, Time: 11
Size: 40, Time: 17
Size: 50, Time: 26
Size: 60, Time: 18
Size: 70, Time: 22
Size: 80, Time: 23
Size: 90, Time: 21
Size: 100, Time: 27
Size: 1000, Time: 28

**Comment by mikaellothman** [comment]
Please note that the test were performed locally with extremely fast access to the Cassandra node with more performant hardware than our prod-servers. The penalty of calling Cassandra will be even bigger in production.

**Comment by MrShish** [comment]
i will be convinced if we benchmark this in an environment similar to production, i really wanna se how this works with a lock across a network..

**Comment by mikaellothman** [comment]
Sure, that would be interesting to see. I will do that....stay tuned..

**Comment by mikaellothman** [comment]
Ok. As promised, here comes results from running in test-env with similar network latency as in prod. I turned out that the current implementation performs even worse (with failures), while the proposed solution in this PR is quite stable:

***Old solution:***
Concurrent threads: 1, Time: 3882
Concurrent threads: 10, Time: 8150
Concurrent threads: 20, Time: 9045
Concurrent threads: 30, Time: 7782
Concurrent threads: 40, Time: 8052
Concurrent threads: 50, Time: 10380
Concurrent threads: 60, Time: 14726
Concurrent threads: 70, Time: 16681 (2 failures)
Concurrent threads: 80, Time: 16769
Concurrent threads: 90, Time: 17621 (2 failures)
Concurrent threads: 100, Time: 19490 (2 failures)
Concurrent threads: 1000, Time: 23328 (121 failures)

***New:***
Concurrent threads: 1, Time: 3885
Concurrent threads: 10, Time: 3697
Concurrent threads: 20, Time: 4479
Concurrent threads: 30, Time: 3104
Concurrent threads: 40, Time: 3145
Concurrent threads: 50, Time: 5037
Concurrent threads: 60, Time: 4635
Concurrent threads: 70, Time: 3165
Concurrent threads: 80, Time: 3083
Concurrent threads: 90, Time: 3148
Concurrent threads: 100, Time: 3058
Concurrent threads: 1000, Time: 3371

**Comment by MrShish** [comment]
ok! perfect! :+1:

**Comment by mikaellothman** [comment]
Thanks @MrShish!

**Pull request merged**
