### PR TITLE
Tweak Cassandra driver settings.

### PR DESCRIPTION
**Pull request by xiaodong-izettle**
Ping @ssprang, verified in test....

### CODE REVIEW

**Comment by xiaodong-izettle** [comment]
F.Y.I, @adamvoncorswant and @progre55...

**Comment by xiaodong-izettle** [comment]
PR in purchase-service will come...

**Comment by progre55** [comment]
👍

**Comment by ssprang** [comment]
Wow, nice, throwing 🍠  at @x1a0 ! :)

**Comment by x1a0** [comment]
Great 👍  @xiaodong-izettle and thank you @ssprang !

@xiaodong-izettle I am curious about how did you verify it in test, will this fix the Cassandra issue we have in prod?

(I think I will try to read driver state and push to influxdb/grafana for purchase and cash-register service see if that helps)

**Comment by xiaodong-izettle** [comment]
I'm not sure actually whether this could anything in prod... But I think it worth trying... :)

**Comment by x1a0** [comment]
@xiaodong-izettle I see. Let's try then :)

**Comment by xiaodong-izettle** [comment]
When I said `verified in test`, I meant this did not break anything...

**Comment by xiaodong-izettle** [comment]
F.Y.I, @adamvoncorswant and @progre55, I'll try this in the evening today around 21:00 in prod...

**Comment by xiaodong-izettle** [comment]
https://github.com/iZettle/purchase-service/pull/772

This is the other part in `purchase-service`...

**Comment by progre55** [comment]
roger, thanks for the heads-up, @xiaodong-izettle

**Comment by adamvoncorswant** [comment]
@xiaodong-izettle : Just curious about how the pooling option worked in the previous default configuration. Do you know?

**Comment by xiaodong-izettle** [comment]
@adamvoncorswant, if you meant the default configuration for `datastax` Cassandra driver, it's 1 for both core and max size, no matter it's local or remote... (At `PoolingOptions::DEFAULTS`, if you want the source code)

The driver uses `Netty` underlying, so I assume the default does make sense...

It's just we are having issues, so I want to tweak this setting... 

Hope I made myself clear... :-)

**Comment by adamvoncorswant** [comment]
Cool, thanks @xiaodong-izettle . Looks good to me!

**Comment by xiaodong-izettle** [comment]
Thanks for merging... :)

**Pull request merged**
