### PR TITLE
CurrencyId: Add 11 missing currencies

### PR DESCRIPTION
**Pull request by adamvoncorswant**
Although quite rare (and some not even used anymore), we still want to
be able to interpret all possible currencies.

The added ones are:
```
AFN
AZN
GHS
MZN
RSD
SDG
SSP
TMT
VEF
ZMW
ZWL
```
Note: To keep the alphabetical order, all lines have been modified, so
this diff is easiest looked at using `--word-diff`

### CODE REVIEW

**Comment by adamvoncorswant** [comment]
ping @oskarwiksten

**Comment by oskarwiksten** [comment]
Running the following command : 
```
$ curl 'http://www.currency-iso.org/dam/downloads/lists/list_one.xml' \
      | xmlstarlet sel -t -m '//CcyNtry' -v 'Ccy' -o ', // ' -v 'CcyNm' -nl \
      | sort \
      | uniq
```

and matching against this list also suggest to add the following currencies:
* `SSP` - South Sudanese pound
* `VEF` - Venezuelan bolívar

You could also argue that `BTC` should be added to this list - but that's for another PR.

**Comment by adamvoncorswant** [comment]
Thanks @oskarwiksten . Added SSP and VEF also. Rebased and force pushed.

**Comment by oskarwiksten** [comment]
Nice @adamvoncorswant .

**Pull request merged**
