### PR TITLE
Java8ify interval

### PR DESCRIPTION
**Pull request by softarn**
Since this is closely related to the java time package I think we should follow their convention with `of` methods for instantiation.

### CODE REVIEW

**Comment by adamvoncorswant** [comment]
Any reason for now allowing the public constructor in parallell?

**Comment by softarn** [comment]
There is no public constructor with this PR

**Comment by adamvoncorswant** [comment]
That's exactly my question: why don't we allow that as well?

**Comment by softarn** [comment]
Ah I see, not sure why they went for this convention. Let's wait for my question a bit: http://programmers.stackexchange.com/questions/322936/why-do-java-time-have-methods-for-creating-objects-instead-of-just-constructors

**Comment by adamvoncorswant** [comment]
Cool. Let's wait then :)

**Comment by softarn** [comment]
Answers are in. So they basically went for them to be able to be in control of which instance to return. For example the `Month` object which returns the enum from the private `ENUMS` cache

```
    public static Month of(int month) {
        if (month < 1 || month > 12) {
            throw new DateTimeException("Invalid value for MonthOfYear: " + month);
        }
        return ENUMS[month - 1];
    }
```

And descriptive power of calling methods i.e. `ofInstant`.

So I don't see that these will apply to `Interval`. I do think we should have the constructor private to only have one way of creating the object and that we should go for `of` because it's the standard of the `java.time` package which this is building on.

**Comment by adamvoncorswant** [comment]
Aight. So, do you think we should merge this as is then?

**Comment by softarn** [comment]
Yes, thanks! I'll make sure to update in the sun.

**Comment by adamvoncorswant** [comment]
Thanks @softarn

**Pull request merged**
